# yaml-language-server: $schema=https://raw.githubusercontent.com/swarmlibs/dockerstack-schema/main/schema/dockerstack-spec.json

services:
  proxy:
    image: ${DOCKER_SERVICE_VAULT_IMAGE:-hashicorp/vault}:${DOCKER_SERVICE_VAULT_IMAGE_TAG:-latest}
    command: proxy -config=/vault/config/vault-proxy.hcl
    ports:
      - target: 8200
        published: 8200
        mode: host
        protocol: tcp
    networks:
      vault:
    configs:
      - source: vault-proxy-config
        target: /vault/config/vault-proxy.hcl
    stop_signal: SIGTERM
    cap_add:
      - IPC_LOCK
    logging:
      options:
        max-size: "12m"
        max-file: "5"
      driver: json-file
    deploy:
      replicas: ${DOCKER_SERVICE_VAULT_REPLICAS:-1}
      placement:
        max_replicas_per_node: 1
      resources:
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        order: stop-first
        monitor: 120s
        parallelism: 1
        failure_action: pause
        max_failure_ratio: 0.1
      rollback_config:
        order: stop-first
        parallelism: 1
        monitor: 120s
        failure_action: pause
        max_failure_ratio: 0.1

networks: 
  # Vault server internal network
  vault:

configs:
  vault-proxy-config:
    name: vault_proxy_config_v1
    file: ./proxy/proxy-config.hcl
    template_driver: golang
